### ISSUE TITLE
Failing to update

### ISSUE THREAD

**Issue by battlestarsc2** [pamods/pamm-atom#12]
When I open this after doing the fix for issue 10 (delete resize.js somewhere deep in those resources: %LOCALAPPDATA%\Uber Entertainment\Planetary Annihilation\pamm\resources\app\assets\js\), it won't update. It seems to try to access %LOCALAPPDATA%\Uber Entertainment\Planetary Annihilation\pamm\resources\app_backup, which doesn't exist. It blames the error on permissions.

**Comment by mereth** [comment]
It's probably because you still have your file explorer in "pamm\resources\app" when pamm try to autoupdate. Use the latest installer instead, which contains the latest version. And after a first "white screen of death", the auto resize should have been disabled by itself and it shouldn't happen anymore.

**Comment by mereth** [comment]
Is your problem has been solved by using the latest installer ?
